# Generated by Django 5.1 on 2024-08-29 21:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('data_nascimento', models.DateField()),
                ('nome', models.CharField(max_length=200)),
                ('academia', models.CharField(blank=True, max_length=200, null=True)),
                ('modalidade', models.CharField(choices=[('BJJ', 'Brazilian Jiu-Jitsu'), ('MMA', 'Mixed Martial Arts'), ('BOX', 'Boxing'), ('MT', 'Muay Thai'), ('JUDO', 'Judo'), ('WREST', 'Wrestling'), ('KARATE', 'Karate'), ('TKD', 'Taekwondo'), ('INI', 'Iniciante')], default='INI', max_length=10)),
            ],
        ),
    ]
