# Generated by Django 5.1 on 2024-08-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField()),
                ('nome', models.CharField(max_length=200)),
                ('academia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_luta', models.DateField()),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('lutas_disputadas', models.IntegerField()),
                ('desistencia', models.IntegerField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='athletes.athlete')),
            ],
        ),
    ]
