# Generated by Django 5.1 on 2024-12-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='telefone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
