# Generated by Django 5.1 on 2024-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='athletes/'),
        ),
    ]
