# Generated by Django 5.1 on 2024-09-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
    ]
