# Generated by Django 5.1 on 2024-08-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='resultado',
            field=models.IntegerField(choices=[(1, 'Atleta 1'), (2, 'Atleta 2'), (0, 'Empate')]),
        ),
    ]
