# Generated by Django 5.1 on 2024-09-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField()),
                ('nome_evento', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('modalidade', models.CharField(choices=[('BJJ', 'Brazilian Jiu-Jitsu'), ('MMA', 'Mixed Martial Arts'), ('BOX', 'Boxing'), ('MT', 'Muay Thai'), ('JUDO', 'Judo'), ('WREST', 'Wrestling'), ('KARATE', 'Karate'), ('TKD', 'Taekwondo'), ('INI', 'Iniciante')], default='INI', max_length=10)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='events.promoter')),
            ],
        ),
    ]
