# Generated by Django 5.1 on 2024-08-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('lutas_disputadas', models.IntegerField()),
                ('desistencia', models.IntegerField()),
            ],
        ),
    ]
