# Generated by Django 5.1 on 2024-08-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('lutas_disputadas', models.IntegerField()),
                ('desistencia', models.IntegerField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cartel', to='athletes.athlete')),
            ],
        ),
    ]
